### ISSUE TITLE
Issue at build

### ISSUE THREAD

**Issue by RyuSP** [Wunkolo/Maple2Tools#1]
On Ubuntu 18.04 64bit:

collect2: error: ld returned 1 exit status
CMakeFiles/Expand.dir/build.make:98: recipe for target 'Expand' failed
make[2]: *** [Expand] Error 1
make[2]: Leaving directory '/home/ryu/Maple2Tools/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/Expand.dir/all' failed
make[1]: *** [CMakeFiles/Expand.dir/all] Error 2
make[1]: Leaving directory '/home/ryu/Maple2Tools/build'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Wunkolo** [comment]
It looks like some kind of linker error. Do you have any more info on the diagnostic message? Something like a `undefined reference` error? It's possible that it's just a Crypto++ library/linking issue.

**Comment by RyuSP** [comment]
Was able to fix the above error, I'm assuming I was on cryptopp 6 instead of 7. Reinstalled Ubuntu/Windows so don't know for sure. However was replaced by this error when using ./Expand
"./Expand: error while loading shared libraries: libcryptopp.so.7: cannot open shared object file: No such file or directory"

**Comment by Wunkolo** [comment]
Looks like a dynamic library is missing.
The latest `crypto++` library is called `libcrypto++-dev` while the [version 6 is explicitly named libcrypto++6](https://packages.ubuntu.com/search?keywords=libcrypto%2B%2B&searchon=names&suite=bionic&section=all).
Be sure to have the latest installed and see if that fixes it. Keep in mind too that the latest version of crypto++ is version **9** so be sure to get that if it is available for your distro.

Eventually I plan to remove crypto++ as a dependency as that is the only difficult-to-integrate-into-cmake thing that is stopping this from being easy to build on Windows and other linux distros(and requires them to be manually installed with their respective package manager).
Let me know how it goes.

**Comment by RyuSP** [comment]
Yep, installing libcrypto++-dev fixed it. Thank you.
