### ISSUE TITLE
Issue with starting it up

### ISSUE THREAD

**Issue by NomKePo** [Wunkolo/Maple2Tools#3]
when i try to open the zip/folder "MapleTools-x64" with Powershell, it just pops up as a WinRAR Window.

**Comment by Wunkolo** [comment]
The zip file is supposed to be extracted so that you see the `.exe` files. Then _those_ are the files that you are to run within powershell/command prompt.

**Comment by NomKePo** [comment]
i did that and it just closed itself after a second

**Comment by Wunkolo** [comment]
You have to run the `.exe` from within a stable powershell window, and not just double-click the `.exe` file
